# Generated by Django 4.0.1 on 2022-01-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.IntegerField()),
                ('name_operation', models.CharField(max_length=30)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('agency', models.IntegerField()),
                ('account', models.IntegerField()),
                ('cpf_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bank.client')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('type_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.operation')),
                ('account_received', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_received', to='bank.account')),
                ('account_shipping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_shipping', to='bank.account')),
            ],
        ),
    ]
