# Generated by Django 4.0.1 on 2022-01-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='max_value',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
